{% set version = "0.20.6" %}

package:
  name: azure-servicemanagement-legacy
  version: {{ version }}

source:
  fn: azure-servicemanagement-legacy-{{ version }}.zip
  url: https://pypi.io/packages/source/a/azure-servicemanagement-legacy/azure-servicemanagement-legacy-{{ version }}.zip
  md5: c883ff8fa3d4f4cb7b9344e8cb7d92a9feca2aa5efd596237aeea89e5c10981d
  

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - python
    - setuptools
    - azure-common
    - requests
    - pyopenssl
  run:
    - python
    - azure-common
    - requests
    - pyopenssl

test:
  imports:
    - azure
    - azure.servicemanagement
    - azure.servicemanagement._http
  commands:
    - python -m unittest discover -p "test_*.py"    

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Legacy Service Management Client Library for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
    - Maxyme
