travis:
  secure:
    BINSTAR_TOKEN: DViUj4Lun1cuP9Um23OwIS5SgzVxq84zZDMSLkMCqpA2oaeJR1PIR/LYgwt7oK2j+XKwboKnLm51REl3zkMAe9zpH5kAedamkwwHOKYmmIGZaH46QiiP/ZDvDDmJuaPJ4nz9buDF5S3xDuuPz1+36nTG8Jn+LKrf2LeNo4p1wiJ+RTtwv2z0G4bhic7WJ2IsY66JHgPzf5Huq/oIOBj0Gw/Bd37YBZgvJuI9deDmMPeYx7dFxNu+Nmjiqlciu9C0IJwK0Dy5GUopmYZhYrBKdLR5hoy68MdK7ZobHiW4BtzntCz9/cYjqJYpRIYyY2Bnip8MfvtA6qjAA0OFd+NgoB+Imalp0WE3d6qc2wb4lD8mQqrTWgFrIw+AuMsP2i/U7yHI3JGUWz+5SqKTXQXvXct1Rup9BT7ArznxhrUOcWxbAozBBBX7MLPkqIugpjnzck4vpN/+HS+6opWdp008e/YtMA3paIAiWEmyr4dxvAN0JOf6ve0NiqyvVZwTH0pvi8PiFEbtu5D7SEyPgnWRXV8HLcKL0gWeufXmOY0Dp15eD1pZq4lVzVql3mRIcHPepgSLXq50uqtcTax/5hy8gB8hbiPnY9ltJo94w9HBGvAgjeL2ziJ6z4NlscTLN7yuSYESiDkvHj3q6iFD8zixqRyVIOwDbNtVbUY2uGRnfeM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
