travis:
  secure:
    BINSTAR_TOKEN: NdKrwIe8Yu+PTtKDFO32MfeH3BOSCyrt2ybhqyEVKZolpM8HXkQA7YAuV2+7liYeLhj78NJqXKTrpnIwELr0ZlCtCPYx1h5TiHbNZwYVsUE2xZiIAZ3+m3ElhGuX4a0HNILIblk2/N54/yWYLL14McaHh1iXozTw6ex+wt8o5F/QQ4KYaHSV2s9qpbxrsdajxl0bf4mteQ+ZwsxxXqXv6NUjySTFTrrm0XF8B3qQCxzefJJ1aYXX3ALBMsevA/krmRJ5mpXfwiFbVvPMC0ef3gOmB/d9gf8zmUp9XFU+DnOIKWEXpegN+ThaGe//dVWHSTLnDAvnEL5p4MdLCzD8TP1ToSJWtFLMEpqk3EnZVLpURApf3+5SQKDRn9jV01uh9ejlGn7HupDP601zlRzOVrWV7IZY3nhIKyZEOQgh0mYbwWQV9vv4a3Lh6JeD4kAygfsdQoEOHDTUg5EKBeazbRgEh+XZM8afBv2SruoTLnMoJ9x7RecIdcl/FhOJm7doiYzckH/yt7nD1i8EWQjKAW8ICggY+chfTxHNqj0SZ7s9sPonkPB7eN1VtwBLcBD0tzRLBt0wlGfyuIlrOv1t01WHwEnt/8nsYr0odbkBlEwNqXBMzzQBC5OeJ2uCd+zNh6lL48GCxz63GqJZpeoqFAnpi2OJTGHGdjbG//+O3Bc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
