travis:
  secure:
    BINSTAR_TOKEN: Swfn9exI4HtaqPXWiclfVouxGM+wjMlzBz4cjrz6MsKLzA7T03GXaTp6/8kw3cnwWfNuN99Uhk2JhKT/dLwVMXIKcp1Y+7GyvRDhDM9FYGN120eiUriQol7YOIARmDKIJhoNY90DnayhroQWrhxqoX4DIUCf5loNcUPrqt0ZXiXnrPNGyRiCcKWz6RAYVSUrwo2fnuJfq3URZxA1UxhsfXIsPbKIBHI0WrPmdprUVAWTFEqhKdB/WnEknRWEWSR32iMO1hPPfprPFJ1OBJaddPraI4MBEuirXI+3MU6/85DPFgMIFearTYQsnWxGzM3KBksdOClK7kmSLUy/59lKF103G/2s20UY+G1eTvimxJ373pH4LgXrOEuijnlDCVDsVTqP1EoJbemIAx5X8Q0+gKGV+LshSCnn4N6InwM7Wbo6xM03+Hm87olNbvhTCAXMkURzqsbtFK8pDVREAqqW3SgtkLy53n+8c4Gnh3I7V+OCA+cE4rONWCnw13NQpIec7giaIc9CY3IoB4bwcxF9mCtx8dEcHT22m1pqgmGnmzdDKUNMetj0YJ4pJOAcL7A0HjnvghxDgwy0yQmKdjtIj9FEK2Cr5DpPKnWCebb0CMj7zjAXXL4+1jmUDku8KP05n5edxvxiXyIssGci6vecNZn0aNf2j9SA8n7MLJngGl8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
