travis:
  secure:
    BINSTAR_TOKEN: sHKZRylL3kcOZDrThjL2ZiNbqiOMtwIxY0MtBtmnCYaAO0T6Otc9uY9qre3/ke91Bs/CE3wMOSOKg2Pg+7EoUURNxblyW6bntGCL8cV9rZ6PCWnoXFfZQvQ5J4eqS2guVjPQjAiFrkIMq3I0R+boqKaVmwjK3D6lW0AuJ+JNmiWKGiO/CPEZjr0u8KpJldSOVxK8S3LUzn/HKAakAicIcM0NHrbDpEmPVqK8h9iVkVUKRD6Of+dPZWRVQwthVJ4MGbxwz1FS3c2c7uDD0pJ2b4J+SZEMakcrfpUywlwpV7cEV5KpnPUguXAUR06R/k831qfbqJ2gggTVfHJSoVv9e3wHvEg9P1+DxJK83O5/TxuzXt1srI5HYCKKMBJXf09U8gXgQb+u1S6yvIW1GrfE8Hfq9lD5UAPw3y07isGDt2krvcjYeviD9rXfoJAnia4z9uU7LEecHG1WCxEF1lApQn61WP53sBzIIGB8hQWKdHzqw8sKxinrKGGrN83jbxKSmiQlBUDcC8ig8geSl6w2ZoInPyj/L58wcuazhX1xynaVPij0+8siM7rhDlyiIeCeTZ8kn6j69weP6J7CKLY2j3+W+mQJ68xyWuAWMjJ98pm4QgOEFHY1NmJSZ05aE88G7CES/0jUdg/IZrnagtfs8QbOe9gswom7sSlspZfBOVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
